config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_xprofile:
    src: xprofile
    dst: ~/.xprofile
  f_gpg-agent.conf:
    src: gnupg/gpg-agent.conf
    dst: ~/.gnupg/gpg-agent.conf
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_mpv.conf:
    src: config/mpv/mpv.conf
    dst: ~/.config/mpv/mpv.conf
  f_autostart.target:
    src: config/systemd/user/autostart.target
    dst: ~/.config/systemd/user/autostart.target
  f_easyeffects.service:
    src: config/systemd/user/easyeffects.service
    dst: ~/.config/systemd/user/easyeffects.service
  f_rofimoji.rc:
    src: config/rofimoji.rc
    dst: ~/.config/rofimoji.rc
  f_config.rasi:
    src: config/rofi/config.rasi
    dst: ~/.config/rofi/config.rasi
  d_gtk-3.0:
    src: config/gtk-3.0
    dst: ~/.config/gtk-3.0
  f_config:
    src: config/ncdu/config
    dst: ~/.config/ncdu/config
  f_picom.conf:
    src: config/picom/picom.conf
    dst: ~/.config/picom/picom.conf
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  d_wezterm:
    src: config/wezterm
    dst: ~/.config/wezterm
  f_yt-dlp_config:
    src: config/yt-dlp/config
    dst: ~/.config/yt-dlp/config
  f_zathurarc:
    src: config/zathura/zathurarc
    dst: ~/.config/zathura/zathurarc
  f_git_config:
    src: config/git/config
    dst: ~/.config/git/config
  d_zsh:
    src: config/zsh
    dst: ~/.config/zsh
    upignore:
    - '.*'
    - '!.zshrc'
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_mimeapps.list:
    src: config/mimeapps.list
    dst: ~/.config/mimeapps.list
  f_config.py:
    src: config/qtile/config.py
    dst: ~/.config/qtile/config.py
variables:
  email: narakhan@disroot.org
  name: narakhan
  public_key: 8F901B0B0B5526AC
profiles:
  knucker:
    dotfiles:
    - ALL
